### ISSUE TITLE
Incorrect answer

### ISSUE THREAD

**Issue by a1div0** [tarantool/luarapidxml#9]
Hello!

When:
Function = `decode`
and input XML = `<root><dbupdate></root>`
(Missed dbupdate closed tag)

then an exception should be thrown, but it doesn't.

Example for Lua:
``` lua
local xml_reader = require('luarapidxml') -- current version (2.0.2)

local xml = '<root><dbupdate></root>'
local ok, parsed_xml = pcall(xml_reader.decode, xml)
if ok then
    print('wrong')
else
    print('correct')
end
```

**Comment by DifferentialOrange** [comment]
> then an exception should be thrown, but it doesn't.

See https://github.com/tarantool/luarapidxml/releases/tag/2.0.1

> Due to exception handling specifics the module doesn't raise Lua errors anymore. Instead, it returns nil, "Error description". (incompatible change)

So for 2.0.2 code you should write
```lua
local xml_reader = require('luarapidxml') -- current version (2.0.2)

local xml = '<root><dbupdate></root>'
local parsed_xml, err = xml_reader.decode(xml)
if err ~= nil then
    print('wrong')
    print(err)
else
    print('correct')
end
```
